<?php

declare(strict_types=1);

/**
 * Class which returns the class map definition
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'shipperValue' => '\\StructType\\ShipperValue',
            'resultFaisabiliteESD' => '\\StructType\\ResultFaisabiliteESD',
            'esdValue' => '\\StructType\\EsdValue',
            'headerValue' => '\\StructType\\HeaderValue',
            'customerValue' => '\\StructType\\CustomerValue',
            'recipientValue' => '\\StructType\\RecipientValue',
            'refValue' => '\\StructType\\RefValue',
            'skybillValue' => '\\StructType\\SkybillValue',
            'skybillParamsValue' => '\\StructType\\SkybillParamsValue',
            'resultExpeditionValue' => '\\StructType\\ResultExpeditionValue',
            'resultGetReservedSkybillWithTypeValue' => '\\StructType\\ResultGetReservedSkybillWithTypeValue',
            'donneurDOrdre' => '\\StructType\\DonneurDOrdre',
            'adresseEnlevement' => '\\StructType\\AdresseEnlevement',
            'adresseEnlevementV2' => '\\StructType\\AdresseEnlevementV2',
            'adresseEnlevementV3' => '\\StructType\\AdresseEnlevementV3',
            'particularitesEsd' => '\\StructType\\ParticularitesEsd',
            'options' => '\\StructType\\Options',
            'resultEnlevementNational' => '\\StructType\\ResultEnlevementNational',
            'infoEnlevement' => '\\StructType\\InfoEnlevement',
            'scheduledValue' => '\\StructType\\ScheduledValue',
            'appointmentValue' => '\\StructType\\AppointmentValue',
            'esdWithRefClientValue' => '\\StructType\\EsdWithRefClientValue',
            'esdWithRefClientValueV2' => '\\StructType\\EsdWithRefClientValueV2',
            'resultReservationExpeditionValue' => '\\StructType\\ResultReservationExpeditionValue',
            'esdValue3' => '\\StructType\\EsdValue3',
            'skybillWithDimensionsValue' => '\\StructType\\SkybillWithDimensionsValue',
            'skybillWithDimensionsValueV2' => '\\StructType\\SkybillWithDimensionsValueV2',
            'skybillWithDimensionsValueV3' => '\\StructType\\SkybillWithDimensionsValueV3',
            'skybillParamsValueV2' => '\\StructType\\SkybillParamsValueV2',
            'resultShippingValue' => '\\StructType\\ResultShippingValue',
            'resultMultiParcelExpeditionValue' => '\\StructType\\ResultMultiParcelExpeditionValue',
            'resultMultiParcelValue' => '\\StructType\\ResultMultiParcelValue',
            'skybillValueV2' => '\\StructType\\SkybillValueV2',
            'resultReservationExpeditionValueV2' => '\\StructType\\ResultReservationExpeditionValueV2',
            'resultGetReservedSkybillValue' => '\\StructType\\ResultGetReservedSkybillValue',
            'resultReservationMultiParcelExpeditionValue' => '\\StructType\\ResultReservationMultiParcelExpeditionValue',
            'resultParcelValue' => '\\StructType\\ResultParcelValue',
            'shipperValueV2' => '\\StructType\\ShipperValueV2',
            'recipientValueV2' => '\\StructType\\RecipientValueV2',
            'refValueV2' => '\\StructType\\RefValueV2',
            'skybillWithDimensionsValueV4' => '\\StructType\\SkybillWithDimensionsValueV4',
            'skybillWithDimensionsValueV5' => '\\StructType\\SkybillWithDimensionsValueV5',
            'skybillWithDimensionsValueV6' => '\\StructType\\SkybillWithDimensionsValueV6',
            'recipientLocalValue' => '\\StructType\\RecipientLocalValue',
            'recipientLocalValueV2' => '\\StructType\\RecipientLocalValueV2',
            'customsValue' => '\\StructType\\CustomsValue',
            'articleValue' => '\\StructType\\ArticleValue',
            'headerValueV2' => '\\StructType\\HeaderValueV2',
            'resultReservationMultiParcelExpeditionValueV2' => '\\StructType\\ResultReservationMultiParcelExpeditionValueV2',
            'resultExpeditionValueV3' => '\\StructType\\ResultExpeditionValueV3',
            'resultMonoParcelExpeditionValue' => '\\StructType\\ResultMonoParcelExpeditionValue',
            'esdResultContraintesAgenceValue' => '\\StructType\\EsdResultContraintesAgenceValue',
            'esdContraintesAgence' => '\\StructType\\EsdContraintesAgence',
            'resultAnnulerEnlevement' => '\\StructType\\ResultAnnulerEnlevement',
            'statut' => '\\StructType\\Statut',
            'entry' => '\\StructType\\Entry',
            'destinatairesDpd' => '\\StructType\\DestinatairesDpd',
            'destinataireDpd' => '\\StructType\\DestinataireDpd',
            'adresseDestinataire' => '\\StructType\\AdresseDestinataire',
            'infoClient' => '\\StructType\\InfoClient',
            'particularites' => '\\StructType\\Particularites',
            'particularitesColisDpd' => '\\StructType\\ParticularitesColisDpd',
            'infoDouanieres' => '\\StructType\\InfoDouanieres',
            'resultPickupOrCollectionRequest' => '\\StructType\\ResultPickupOrCollectionRequest',
            'skybillValueBase' => '\\StructType\\SkybillValueBase',
            'resultShippingInfo' => '\\StructType\\ResultShippingInfo',
            'error' => '\\StructType\\Error',
            'detail' => '\\StructType\\Detail',
            'shippingInfo' => '\\StructType\\ShippingInfo',
            'resultGetRouting' => '\\StructType\\ResultGetRouting',
            'geopostResult' => '\\StructType\\GeopostResult',
            'faisabiliteESD' => '\\StructType\\FaisabiliteESD',
            'faisabiliteESDResponse' => '\\StructType\\FaisabiliteESDResponse',
            'shippingV2' => '\\StructType\\ShippingV2',
            'shippingV2Response' => '\\StructType\\ShippingV2Response',
            'getReservedSkybillWithTypeAndModeAuth' => '\\StructType\\GetReservedSkybillWithTypeAndModeAuth',
            'getReservedSkybillWithTypeAndModeAuthResponse' => '\\StructType\\GetReservedSkybillWithTypeAndModeAuthResponse',
            'getReservedSkybillWithType' => '\\StructType\\GetReservedSkybillWithType',
            'getReservedSkybillWithTypeResponse' => '\\StructType\\GetReservedSkybillWithTypeResponse',
            'creerEnlevementNational' => '\\StructType\\CreerEnlevementNational',
            'creerEnlevementNationalResponse' => '\\StructType\\CreerEnlevementNationalResponse',
            'shippingV3' => '\\StructType\\ShippingV3',
            'shippingV3Response' => '\\StructType\\ShippingV3Response',
            'getReservedSkybillWithTypeAndModeByReservation' => '\\StructType\\GetReservedSkybillWithTypeAndModeByReservation',
            'getReservedSkybillWithTypeAndModeByReservationResponse' => '\\StructType\\GetReservedSkybillWithTypeAndModeByReservationResponse',
            'shippingWithESDOnlyV2' => '\\StructType\\ShippingWithESDOnlyV2',
            'shippingWithESDOnlyV2Response' => '\\StructType\\ShippingWithESDOnlyV2Response',
            'shippingMultiParcel' => '\\StructType\\ShippingMultiParcel',
            'shippingMultiParcelResponse' => '\\StructType\\ShippingMultiParcelResponse',
            'shippingWithReservationV2' => '\\StructType\\ShippingWithReservationV2',
            'shippingWithReservationV2Response' => '\\StructType\\ShippingWithReservationV2Response',
            'shipping' => '\\StructType\\Shipping',
            'shippingResponse' => '\\StructType\\ShippingResponse',
            'getReservedSkybill' => '\\StructType\\GetReservedSkybill',
            'getReservedSkybillResponse' => '\\StructType\\GetReservedSkybillResponse',
            'shippingMultiParcelWithReservation' => '\\StructType\\ShippingMultiParcelWithReservation',
            'shippingMultiParcelWithReservationResponse' => '\\StructType\\ShippingMultiParcelWithReservationResponse',
            'shippingMultiParcelV4' => '\\StructType\\ShippingMultiParcelV4',
            'shippingMultiParcelV4Response' => '\\StructType\\ShippingMultiParcelV4Response',
            'shippingMultiParcelV5' => '\\StructType\\ShippingMultiParcelV5',
            'shippingMultiParcelV5Response' => '\\StructType\\ShippingMultiParcelV5Response',
            'shippingMultiParcelWithReservationV3' => '\\StructType\\ShippingMultiParcelWithReservationV3',
            'shippingMultiParcelWithReservationV3Response' => '\\StructType\\ShippingMultiParcelWithReservationV3Response',
            'shippingMultiParcelV2' => '\\StructType\\ShippingMultiParcelV2',
            'shippingMultiParcelV2Response' => '\\StructType\\ShippingMultiParcelV2Response',
            'shippingV6' => '\\StructType\\ShippingV6',
            'shippingV6Response' => '\\StructType\\ShippingV6Response',
            'shippingWithReservation' => '\\StructType\\ShippingWithReservation',
            'shippingWithReservationResponse' => '\\StructType\\ShippingWithReservationResponse',
            'shippingV7' => '\\StructType\\ShippingV7',
            'shippingV7Response' => '\\StructType\\ShippingV7Response',
            'rechercherContraintesEnlevement' => '\\StructType\\RechercherContraintesEnlevement',
            'rechercherContraintesEnlevementResponse' => '\\StructType\\RechercherContraintesEnlevementResponse',
            'annulerEnlevements' => '\\StructType\\AnnulerEnlevements',
            'annulerEnlevementsResponse' => '\\StructType\\AnnulerEnlevementsResponse',
            'creerEnlevementEurope' => '\\StructType\\CreerEnlevementEurope',
            'creerEnlevementEuropeResponse' => '\\StructType\\CreerEnlevementEuropeResponse',
            'shippingWithReservationAndESDWithRefClient' => '\\StructType\\ShippingWithReservationAndESDWithRefClient',
            'shippingWithReservationAndESDWithRefClientResponse' => '\\StructType\\ShippingWithReservationAndESDWithRefClientResponse',
            'getReservedSkybillWithTypeAndMode' => '\\StructType\\GetReservedSkybillWithTypeAndMode',
            'getReservedSkybillWithTypeAndModeResponse' => '\\StructType\\GetReservedSkybillWithTypeAndModeResponse',
            'shippingV4' => '\\StructType\\ShippingV4',
            'shippingV4Response' => '\\StructType\\ShippingV4Response',
            'shippingWithReservationAndESDWithRefClientPC' => '\\StructType\\ShippingWithReservationAndESDWithRefClientPC',
            'shippingWithReservationAndESDWithRefClientPCResponse' => '\\StructType\\ShippingWithReservationAndESDWithRefClientPCResponse',
            'shippingV5' => '\\StructType\\ShippingV5',
            'shippingV5Response' => '\\StructType\\ShippingV5Response',
            'shippingMultiParcelWithReservationV2' => '\\StructType\\ShippingMultiParcelWithReservationV2',
            'shippingMultiParcelWithReservationV2Response' => '\\StructType\\ShippingMultiParcelWithReservationV2Response',
            'shippingWithESDOnly' => '\\StructType\\ShippingWithESDOnly',
            'shippingWithESDOnlyResponse' => '\\StructType\\ShippingWithESDOnlyResponse',
            'getShippingInformation' => '\\StructType\\GetShippingInformation',
            'getShippingInformationResponse' => '\\StructType\\GetShippingInformationResponse',
            'getRouting' => '\\StructType\\GetRouting',
            'getRoutingResponse' => '\\StructType\\GetRoutingResponse',
            'shippingMultiParcelV3' => '\\StructType\\ShippingMultiParcelV3',
            'shippingMultiParcelV3Response' => '\\StructType\\ShippingMultiParcelV3Response',
        ];
    }
}
